### ISSUE TITLE
Population and Demographics Assessment

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/lebanon-economic-monitor#2]
To overcome gaps in official demographic statistics, the team has turned to private sector data sources. In their book, “The Narrow Corridor,” Daron Acemoglu and James Robinson suggested that Lebanon has not conducted a population census since 1932. The task is to obtain and plot national and regional (as disaggregated as possible) population data, either monthly and annually.  

```[tasklist]
### Proposal
- [ ] https://github.com/datapartnership/operations/issues/643
```

```[tasklist]
### Tasks  
- [ ] #21
- [ ] https://github.com/datapartnership/lebanon-economic-monitor/issues/23
- [ ] https://github.com/datapartnership/lebanon-economic-monitor/issues/24
- [ ] https://github.com/datapartnership/lebanon-economic-monitor/pull/25
```

**Comment by SahitiSarva** [comment]
For population, we have with us data from Meta using their analysis (which also employs the last available census information). HSRL data has been extracted and uploaded to SharePoint from meta's AWS bucket.
